---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# demopkg

<!-- badges: start -->
<!-- badges: end -->

The goal of demopkg is to provide data and analysis code for the paper "Facial resemblance increases the attractiveness of same-sex faces more than other-sex faces" (DeBruine, 2004).

## Installation

You can install the development version of demopkg from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("debruine/demopkg")
```

## Example


```{r example}
library(demopkg)

# load data from DeBruine (2004)
data("self_res_att")
```


```{r female-faces}
# analyse female faces
apa_t_pair(x = self_res_att$f_self,
           y = self_res_att$f_non,
           dv = "preferences for female faces",
           level1 = "participants who resembled those faces",
           level2 = "non-self participants")
```

```{r male-faces}
# analyse male faces
apa_t_pair(x = self_res_att$m_self,
           y = self_res_att$m_non,
           dv = "preferences for male faces",
           level1 = "participants who resembled those faces",
           level2 = "non-self participants")
```

